// <auto-generated />
using System;
using Finals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Finals.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210417083726_CreateOrderForm")]
    partial class CreateOrderForm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Finals.Models.Order", b =>
                {
                    b.Property<int>("OrderKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceSerKey")
                        .HasColumnType("int");

                    b.HasKey("OrderKey");

                    b.HasIndex("ServiceSerKey");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Finals.Models.Service", b =>
                {
                    b.Property<int>("SerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SerKey");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Finals.Models.Order", b =>
                {
                    b.HasOne("Finals.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceSerKey");

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
